### ISSUE TITLE
Execute client synchronously

### ISSUE THREAD

**Issue by chuongddh-zz** [linkedin/Zopkio#105]
Hello,

My test involves multiple client execution, is there a way I can set Zopkio to execute next client after the first one is finishes and closes ssh session?

Thanks,
Chuong

**Comment by stale2000** [comment]
:+1:

**Comment by keyosk** [comment]
@arpras do you have any timeline for when this enhancement will be addressed?

**Comment by arpras** [comment]
I don't fully follow the question, but can we use the test ordering feature of zopkio to help with this and have separate test per client ?

If the above doesn't make sense we probably need to write a wrapper to do this(or create a test recipe). In terms on inherent support for this in Zopkio I am not sure If I will be able to add something in the near time. I will be super happy to merge any pull request though.

Thanks

**Comment by stale2000** [comment]
Hello @arpras, I'm on the same team with Chuong at Pubnub.

let me give you an example of what we are doing/looking for:

Imagine I am testing a login system.

For this test, I need to make GET requests that do the following:

Create ad account
Log in a user to that account
Modify some account details
Get those account details.

In that order.  Because you have to create the account first, then log in, then modify, for all the api calls to work.

This flow would be a single test.

Right now, in the framework, my intuition would be to do the following:

``` python
def test_modify_user():
    client.start("/create")
    client.start("/login")
    client.start("/modify")
    client.start("/get")
```

I'm told that this wouldn't work, as the clients aren't guaranteed to sequentially run AND finish each request in order. For example, the user needs to exist before the login request happens.  **Is the correct?**

One way to solve this problem, as you suggested, is to create a separate client for each test.

So I would do the following

``` python
def test_modify_user():
    client.start("create_login_modify_get_client")
```

and the client would do something like:

``` python
create_login_modify_get_client()
    requests("create")
    requests("login")
    requests("modify")
    requests("get")
```

The problem with this is that lets say I have 20 API calls that I want to test, and I want to have hundreds of tests that test them in different orders.

Would I have to create a client for each api test ordering?
ie 
client_call_1_2_3_4...20
and a client_2_1_3_4_5 
and a client_5_6_2_1, ect.

That doesn't seem optimal.  One way to "solve" this is to send a list of actions to a single client, in some sort of array  IE ["create", "login", "modify, "get"].  But you start to run into problems there, such as what happens when your login command requires a user_id that is returned by the create command?  (or one of the other 20 api endpoints).  What happens when you want to do more complicated logic based on the return values?

It would be much easier if in each test you could guarantee ordering in some way.  

IE

``` python
def test_modify_user():
    client.start("/create")
    do stuff
    client.start("/login")
    do stuff
    client.start("/modify")
    do stuff
    client.start("/get")
```

Does this make sense, or is there some huge problem with this ordering philosophy that we are missing?  Or do to have any recommendations for how to go about testing something like this using Zopkio?  

Also what do you mean by wrapper, or test recipe?

**Comment by arpras** [comment]
Please let me know if the below would work for your need ?

When you do client.start() you can pass an optional argument to run things synchronously.

---- Relevant Code in adhoc_deployer.py----
`with get_ssh_client(hostname, username=runtime.get_username(), password=runtime.get_password()) as ssh:
      exec_with_env(ssh, command, msg="Failed to start", env=env, sync=configs.get('sync', False))`

This will trigger the below function in remote_helper.py

`def better_exec_command(ssh, command, msg):`
"""Uses paramiko to execute a command but handles failure by raising a ParamikoError if the command fails.
  Note that unlike paramiko.SSHClient.exec_command this is *\* not asynchronous*\* because we wait until the exit status is known"""

You can read through the implementation. This will actually wait till the command is done. Details here : http://paramiko-docs.readthedocs.org/en/latest/api/channel.html#paramiko.channel.Channel.recv_exit_status

Seems like this is what you want.(hopefully :))

Its also used in the examples.
`client_deployer.start("client1", configs={"args": "localhost 8001 1 2".split(), "sync": True})
client_deployer.start("client1", configs={"args": "localhost 8002 1 2 3".split(), "sync": True})`

**Comment by arpras** [comment]
> > Also what do you mean by wrapper, or test recipe?
> > By wrapper I meant you can extend the existing deployer and create a new deployer for your needs which enforces rules you need.

Test Recipes are a concept of reusing the test by changing the parameters. For example you can take a look at recipes.py

**Comment by arpras** [comment]
Can I close this ?

**Comment by chuongddh-zz** [comment]
Hi Arpras,

Thanks for following up. We actually always have "sync"=True in all tests. And the idea of recipes is nice but not applicable for sharing test data between test cases. We will try to resolve this from the client execution side.

Please close this if you see fit.

Kind regards,
Chuong
