### ISSUE TITLE
naarad.config() exception with Zopkio 0.2.0

### ISSUE THREAD

**Issue by chuongddh** [linkedin/Zopkio#81]
Hello,

I recently upgraded Zopkio from 0.16 to 0.2.0. And in the runtime I encounter the following exception. It seems api for naarad.config() has changed. Can you please clarify the impact of this change and what is the expected usage of naarad.config()?
"
Traceback (most recent call last):
  File "/usr/local/bin/zopkio", line 9, in <module>
    load_entry_point('zopkio==0.2.0', 'console_scripts', 'zopkio')()
  File "/Library/Python/2.7/site-packages/zopkio/__main__.py", line 148, in main
    test_runner.run()
  File "/Library/Python/2.7/site-packages/zopkio/test_runner.py", line 126, in run
    config.naarad_id = naarad_obj.signal_start(self.dynamic_config_module.naarad_config())
TypeError: naarad_config() takes at least 1 argument (0 given)" 

Thanks,
Chuong

**Comment by jdehrlich** [comment]
Hi, sorry for breaking backwards compatability, I will implement a fix and support both no arguments and 1 argument in the next micro version (hopefully by EOD friday at latest). The reason for this change was to simplify the new api by removing the passed in mapping. This is because instead of using the passed in dictionary, the same configs can be accessed using runtime.get_active_config(config_option, default=None).

**Comment by jdehrlich** [comment]
this issue should be fixed in 0.2.1, please reopen if a new issue arises

**Comment by chuongddh** [comment]
Hi Joshua,

Thank you so much for delivering resolution so quick.

Best Regards
Chuong
